(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const brand=document.querySelector('.brand');if(brand&&!reduced){requestAnimationFrame(()=>brand.classList.add('power-on'));setTimeout(()=>brand.classList.remove('power-on'),1100)}document.querySelectorAll('img').forEach((img,i)=>{img.decoding='async';if(i>5)img.loading='lazy'});const animated=document.querySelectorAll('.trust-strip,.process ol,.compact-services,.work-gallery,.map-card');if(!reduced&&'IntersectionObserver'in window){animated.forEach(el=>el.classList.add('motion-ready'));const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('motion-in');if(e.target.classList.contains('map-card'))e.target.classList.add('map-energized');io.unobserve(e.target)}}),{threshold:.16});animated.forEach(el=>io.observe(el))}else animated.forEach(el=>el.classList.add('motion-in','map-energized'));const map=document.querySelector('.map-card');if(map){const signal=document.createElement('span');signal.className='map-energy-signal';signal.setAttribute('aria-hidden','true');map.append(signal);const panel=document.createElement('div');panel.className='map-city-panel';panel.innerHTML='<small>JEFF ELECTRIC POWER GRID</small><strong>Southeast Houston service umbrella</strong><span>Tap a community to explore our residential service area.</span>';map.append(panel);document.querySelectorAll('.place').forEach(place=>{place.tabIndex=0;place.setAttribute('role','button');const activate=()=>{document.querySelectorAll('.place').forEach(p=>p.classList.remove('active'));place.classList.add('active');const name=place.textContent.trim();panel.innerHTML='<small>RESIDENTIAL SERVICE AREA</small><strong>'+name+'</strong><span>Call Jeff Electric to confirm availability for your address.</span>'};place.addEventListener('click',activate);place.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})})}const formatPhone=input=>input&&input.addEventListener('input',()=>{const n=input.value.replace(/\D/g,'').slice(0,10);input.value=n.length>6?'('+n.slice(0,3)+') '+n.slice(3,6)+'-'+n.slice(6):n.length>3?'('+n.slice(0,3)+') '+n.slice(3):n});formatPhone(document.querySelector('input[name="fi-phone-phoneNumber"]'));
if(matchMedia('(max-width:720px)').matches){const hero=document.querySelector('.hero'),form=document.querySelector('.contact form');if(hero&&form&&!document.querySelector('#mobile-quote')){const quick=document.createElement('section');quick.id='mobile-quote';quick.className='mobile-quick-quote';quick.innerHTML='<div class="mobile-quick-head"><p class="eyebrow"><span></span> QUICK REQUEST</p><h2>Get a quote or<br><em>send us a photo.</em></h2><p>Tell us the basics. No electrical terminology needed.</p></div>';hero.insertAdjacentElement('afterend',quick);quick.append(form);form.classList.remove('reveal');form.classList.add('mobile-quick-form','is-visible');const service=form.querySelector('select[name="fi-select-serviceType"]');if(service){service.value='Something else';service.required=false;service.closest('label')?.classList.add('mobile-optional-hide')}const pref=form.querySelector('select[name="fi-select-preferredContact"]');pref?.closest('label')?.classList.add('mobile-optional-hide');const message=form.querySelector('textarea[name="fi-text-message"]');if(message){message.rows=3;message.placeholder='What is happening, what do you want installed, or what are you unsure about?'}const photo=form.querySelector('input[type="file"]');if(photo)photo.closest('label')?.classList.add('mobile-photo-field');const submit=form.querySelector('button[type="submit"]');if(submit)submit.innerHTML='Send Request <span>→</span>';const lower=document.querySelector('.contact');if(lower){const note=document.createElement('a');note.className='button button-outline mobile-back-to-quote';note.href='#mobile-quote';note.textContent='Send a service request ↑';lower.querySelector('.contact-copy')?.append(note)}document.querySelectorAll('.mobile-bar a[href="#contact"],.hero-actions a[href="#contact"],.nav a[href="#contact"]').forEach(a=>a.href='#mobile-quote');const mobileBarQuote=document.querySelector('.mobile-bar a:last-child');if(mobileBarQuote){mobileBarQuote.href='#mobile-quote';mobileBarQuote.textContent='Get a Quote'}}}})();
(()=>{const panel=document.querySelector('.map-city-panel');if(panel)panel.innerHTML='<small>SOUTHEAST HOUSTON SERVICE AREA</small><strong>Local residential electrical service</strong><span>Tap a community to explore the area. Service-area illustration — call to confirm your address.</span>'})();
(()=>{const old=document.getElementById('jeff-mobile-header-layout');if(old)old.remove();const style=document.createElement('style');style.id='jeff-mobile-header-layout';style.textContent='@media(max-width:720px){.site-header{height:156px!important;min-height:156px!important;padding:8px 16px 6px!important;display:grid!important;grid-template-columns:1fr 48px!important;grid-template-rows:72px 48px 22px!important;align-items:center!important;gap:0!important;overflow:visible!important}.brand{grid-column:1/3!important;grid-row:1/3!important;justify-self:center!important;align-self:center!important;display:grid!important;grid-template-columns:1fr!important;grid-template-rows:72px 48px!important;justify-items:center!important;align-items:center!important;gap:0!important;width:min(360px,calc(100vw - 32px))!important;max-width:100%!important;min-width:0!important}.brand-icon{grid-row:1!important;width:72px!important;height:72px!important;flex:none!important}.brand-wordmark{grid-row:2!important;width:min(330px,calc(100vw - 44px))!important;max-width:none!important;height:auto!important}.header-actions{display:none!important}.menu-button{display:grid!important;place-items:center!important;grid-column:2!important;grid-row:3!important;justify-self:end!important;align-self:center!important;position:static!important;margin:0!important;padding:0!important;width:44px!important;min-width:44px!important;height:22px!important;min-height:22px!important;font-size:25px!important;line-height:1!important}.nav{top:156px!important;left:0!important;right:0!important;width:100%!important;max-height:calc(100dvh - 156px)!important;overflow-y:auto!important}.hero{scroll-margin-top:156px!important}}';document.head.appendChild(style)})();
(()=>{const style=document.createElement('style');style.id='jeff-map-remove-water';style.textContent='.map-card:before{display:none!important}';document.head.appendChild(style)})();
(()=>{const old=document.getElementById('jeff-map-clean');if(old)old.remove();const style=document.createElement('style');style.id='jeff-map-clean';style.textContent=`
.map-card{background:radial-gradient(circle at 50% 38%,rgba(242,178,26,.07),transparent 42%),linear-gradient(180deg,#0b0d0b 0%,#070807 100%)!important;border-color:#e9e5da!important;box-shadow:0 18px 42px rgba(0,0,0,.22),inset 0 0 0 1px rgba(255,255,255,.02)!important;overflow:hidden!important}
.map-card:before{display:none!important}.map-card:after{display:none!important}
.map-grid{opacity:.035!important;background-size:88px 88px!important;transform:none!important}
.coverage-zone{left:11%!important;top:18%!important;width:72%!important;height:57%!important;border:0!important;border-radius:46% 40% 44% 42%!important;clip-path:none!important;background:radial-gradient(ellipse at center,rgba(242,178,26,.15) 0%,rgba(242,178,26,.08) 48%,rgba(242,178,26,.025) 72%,transparent 82%)!important;outline:1px solid rgba(242,178,26,.16)!important;box-shadow:0 0 34px rgba(242,178,26,.05)!important;animation:none!important;transform:none!important}
.map-route{height:3px!important;opacity:.62!important;background:#a7a797!important;border-radius:999px!important;box-shadow:0 1px 6px rgba(0,0,0,.28)!important;animation:none!important}
.route-45{height:4px!important;background:#d4c47f!important;opacity:.78!important}.route-225{background:#aeb2a6!important}.route-beltway,.route-bay{height:2px!important;opacity:.44!important;background:#879087!important}
.route-label{padding:5px 8px!important;border:1px solid rgba(255,255,255,.07)!important;border-radius:999px!important;background:rgba(10,12,10,.88)!important;color:#cbc5af!important;font-size:6px!important;letter-spacing:.08em!important;box-shadow:none!important}
.place{min-height:28px!important;padding:6px 9px!important;border-radius:999px!important;background:rgba(7,8,7,.88)!important;border:1px solid rgba(255,255,255,.07)!important;color:#f6f3ea!important;font-size:8px!important;letter-spacing:.08em!important;box-shadow:0 7px 16px rgba(0,0,0,.2)!important;backdrop-filter:blur(5px)!important}
.place i{width:8px!important;height:8px!important;flex:0 0 8px!important;border:0!important;background:var(--gold)!important;box-shadow:0 0 0 4px rgba(242,178,26,.13)!important;animation:none!important}
.place:hover,.place:focus,.place.active{background:#12130f!important;border-color:rgba(242,178,26,.35)!important;color:#fff!important;transform:none!important}
.map-pin{width:44px!important;height:44px!important;border-radius:50%!important;box-shadow:0 0 0 9px rgba(242,178,26,.08),0 8px 20px rgba(0,0,0,.3)!important}
.map-label{display:none!important}
.map-energy-signal{display:none!important}
.map-legend{left:12px!important;right:12px!important;bottom:12px!important;padding:12px 14px!important;background:rgba(6,7,6,.92)!important;border:1px solid rgba(255,255,255,.05)!important;border-left:3px solid var(--gold)!important;box-shadow:0 10px 24px rgba(0,0,0,.2)!important;backdrop-filter:blur(6px)!important}
.map-city-panel{background:linear-gradient(180deg,#151715,#0d0f0d)!important;border:1px solid rgba(242,178,26,.24)!important;border-left:4px solid var(--gold)!important;box-shadow:0 14px 30px rgba(0,0,0,.18)!important}
@media(max-width:720px){.map-card{height:410px!important;margin-bottom:108px!important}.map-grid{opacity:.025!important;background-size:96px 96px!important}.coverage-zone{left:10%!important;top:19%!important;width:76%!important;height:55%!important}.map-city-panel{left:0!important;right:0!important;top:auto!important;bottom:-98px!important;width:100%!important;min-height:88px!important;padding:14px 15px!important}.map-city-panel small{font-size:7px!important}.map-city-panel strong{font-size:13px!important}.map-city-panel span{font-size:9px!important;line-height:1.5!important}.place{font-size:7px!important;padding:5px 7px!important}.route-label{font-size:5px!important}.map-legend{left:8px!important;right:8px!important;bottom:8px!important;padding:10px 11px!important}}
`;document.head.appendChild(style)})();
(()=>{const pin=document.querySelector('.map-pin');if(!pin)return;pin.classList.add('jeff-logo-pin');pin.innerHTML='<img src="./public/brand/jeff-electric-mark.png" alt="Jeff Electric service hub">';const old=document.getElementById('jeff-map-logo-pin');if(old)old.remove();const style=document.createElement('style');style.id='jeff-map-logo-pin';style.textContent=`
.jeff-logo-pin{width:64px!important;height:64px!important;border-radius:18px!important;background:#0b0b0b!important;border:2px solid var(--gold)!important;display:grid!important;place-items:center!important;transform:none!important;z-index:6!important;box-shadow:0 0 0 8px rgba(242,178,26,.10),0 10px 24px rgba(0,0,0,.38)!important;overflow:visible!important}
.jeff-logo-pin img{width:46px!important;height:46px!important;display:block!important;object-fit:contain!important;filter:drop-shadow(0 0 6px rgba(242,178,26,.22))!important;position:relative!important;z-index:2!important}
.jeff-logo-pin:before,.jeff-logo-pin:after{content:""!important;position:absolute!important;pointer-events:none!important}
.jeff-logo-pin:before{inset:-10px!important;border-radius:25px!important;border:1px solid rgba(242,178,26,.38)!important;animation:jeffLogoPulse 2.4s ease-in-out infinite!important}
.jeff-logo-pin:after{inset:-22px!important;border-radius:34px!important;background:radial-gradient(circle,rgba(242,178,26,.20) 0%,rgba(242,178,26,.08) 40%,transparent 72%)!important;z-index:-1!important;animation:jeffLogoGlow 2.4s ease-in-out infinite!important}
@keyframes jeffLogoPulse{0%,100%{transform:scale(1);opacity:.48}50%{transform:scale(1.13);opacity:1}}
@keyframes jeffLogoGlow{0%,100%{transform:scale(.96);opacity:.42}50%{transform:scale(1.18);opacity:.9}}
@media(max-width:720px){.jeff-logo-pin{width:56px!important;height:56px!important}.jeff-logo-pin img{width:40px!important;height:40px!important}}
@media(prefers-reduced-motion:reduce){.jeff-logo-pin:before,.jeff-logo-pin:after{animation:none!important}}
`;document.head.appendChild(style)})();
(()=>{const old=document.getElementById('jeff-polished-black-header');if(old)old.remove();const style=document.createElement('style');style.id='jeff-polished-black-header';style.textContent=`
@media(max-width:720px){
html,body{background:#000!important}
.site-header{background:#000!important;background-image:none!important;border-bottom:1px solid rgba(255,255,255,.07)!important;box-shadow:none!important;isolation:isolate!important}
.site-header:before,.site-header:after{content:none!important;display:none!important}
.brand{background:transparent!important;box-shadow:none!important;filter:none!important}
.brand:before,.brand:after{content:none!important;display:none!important}
.brand-icon,.brand-wordmark{background:transparent!important}
.nav{background:#050505!important;border-bottom:1px solid rgba(255,255,255,.07)!important;box-shadow:0 18px 30px rgba(0,0,0,.38)!important}
.hero{background:#000!important;background-image:none!important;border-top:0!important;box-shadow:none!important}
.hero:before,.hero:after{content:none!important;display:none!important}
.site-header+.hero{border-top:0!important}
}
`;document.head.appendChild(style)})();
(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const style=document.createElement('style');style.id='jeff-entry-lightning-style';style.textContent=`
.jeff-entry-lightning{position:fixed;inset:0;z-index:2147483647;pointer-events:none;overflow:hidden;background:transparent;animation:jeffSurgeExit .68s linear forwards}
.jeff-entry-lightning:before{content:"";position:absolute;inset:0;background:#fff;opacity:0;animation:jeffFlash .48s linear forwards}
.jeff-entry-lightning:after{content:"";position:absolute;inset:-12%;background:radial-gradient(circle at 50% 44%,rgba(255,245,190,.38),rgba(242,178,26,.16) 28%,transparent 62%);opacity:0;animation:jeffAfterglow .66s ease-out forwards}
.jeff-strike{position:absolute;inset:-8% -6%;width:112%;height:116%;filter:drop-shadow(0 0 5px #fff) drop-shadow(0 0 13px rgba(255,236,160,.95)) drop-shadow(0 0 28px rgba(242,178,26,.92));opacity:0;animation:jeffStrike .52s steps(2,end) forwards}
.jeff-strike svg{width:100%;height:100%;overflow:visible}
.jeff-strike .core{fill:none;stroke:#fff;stroke-width:5.5;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke}
.jeff-strike .gold{fill:none;stroke:#f2b21a;stroke-width:11;stroke-linecap:round;stroke-linejoin:round;opacity:.48;vector-effect:non-scaling-stroke}
.jeff-strike .branch{fill:none;stroke:#fff7d8;stroke-width:2.4;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke;opacity:0}
.jeff-strike .b1{animation:jeffBranchFlash .26s .06s linear forwards}.jeff-strike .b2{animation:jeffBranchFlash .22s .12s linear forwards}.jeff-strike .b3{animation:jeffBranchFlash .18s .18s linear forwards}.jeff-strike .b4{animation:jeffBranchFlash .16s .23s linear forwards}
.brand.jeff-entry-powered .brand-icon{animation:jeffEntryLogoPower .46s cubic-bezier(.2,.8,.2,1)!important}
@keyframes jeffFlash{0%{opacity:0}4%{opacity:.96}9%{opacity:.06}15%{opacity:.56}21%{opacity:.02}31%{opacity:.24}43%,100%{opacity:0}}
@keyframes jeffAfterglow{0%,20%{opacity:0}29%{opacity:.78}47%{opacity:.28}100%{opacity:0}}
@keyframes jeffStrike{0%{opacity:0;transform:scale(.985)}5%{opacity:1}13%{opacity:.22}18%{opacity:1}29%{opacity:.7;transform:scale(1.01)}43%{opacity:.12}58%,100%{opacity:0;transform:scale(1.015)}}
@keyframes jeffBranchFlash{0%{opacity:0;stroke-dasharray:0 1000}18%{opacity:1;stroke-dasharray:1000 0}55%{opacity:.9}100%{opacity:0}}
@keyframes jeffSurgeExit{0%,80%{opacity:1}100%{opacity:0}}
@keyframes jeffEntryLogoPower{0%{filter:brightness(.45) drop-shadow(0 0 0 transparent);transform:scale(.9)}38%{filter:brightness(1.9) drop-shadow(0 0 22px #fff) drop-shadow(0 0 38px #f2b21a);transform:scale(1.12)}68%{filter:brightness(1.18) drop-shadow(0 0 14px #f2b21a);transform:scale(.98)}100%{filter:none;transform:none}}
`;document.head.appendChild(style);const layer=document.createElement('div');layer.className='jeff-entry-lightning';layer.setAttribute('aria-hidden','true');layer.innerHTML=`<div class="jeff-strike"><svg viewBox="0 0 1000 1200" preserveAspectRatio="none" aria-hidden="true"><path class="gold" d="M646 -30 L548 143 L593 223 L472 348 L520 430 L391 572 L442 654 L317 806 L366 884 L250 1048 L298 1235"/><path class="core" d="M646 -30 L548 143 L593 223 L472 348 L520 430 L391 572 L442 654 L317 806 L366 884 L250 1048 L298 1235"/><path class="branch b1" d="M527 371 L690 278 L647 392 L810 341"/><path class="branch b2" d="M438 657 L257 545 L306 694 L135 626"/><path class="branch b3" d="M358 840 L520 756 L484 889 L646 828"/><path class="branch b4" d="M571 187 L733 98 L702 224 L856 171"/></svg></div>`;document.body.appendChild(layer);setTimeout(()=>{document.querySelector('.brand')?.classList.add('jeff-entry-powered')},300);setTimeout(()=>{document.querySelector('.brand')?.classList.remove('jeff-entry-powered');layer.remove();style.remove()},760)})();
